# Generated by Django 2.1.3 on 2018-11-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('momsn', models.IntegerField(max_length=65535)),
                ('transmit_time', models.CharField(max_length=17)),
                ('iridium_latitude', models.FloatField()),
                ('iridium_longitude', models.FloatField()),
                ('iridium_cep', models.FloatField()),
                ('data', models.CharField(max_length=150000)),
            ],
        ),
    ]
